server:
  port: 80

#服务名
spring:
  application:
    name: gateway
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        locator:
          enabled: false
          lower-case-service-id: true
    gateway:
      routes:
        - id:  hello-api
          uri: lb://hello-server
          predicates:
            - Path=/hello/**
jwt:
  filter:
    skipAuthUrls:
    - /hello/login
    - aaa
